pip uninstall GDAL
pip uninstall imageio-ffmpeg
pip uninstall imageio
pip uninstall pyproj
pip uninstall astropy
pip uninstall astroML
pip uninstall pygame
pip uninstall torch
pip uninstall torchvision
pip uninstall pyarrow
pip uninstall bokeh
pip uninstall scikit-image